---
apiVersion: v1
kind: Service
metadata:
  name: petitions-exporter
  namespace: metrics
  labels:
    app: petitions-exporter
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: petitions-exporter
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petitions-exporter
  namespace: metrics
spec:
  selector:
    matchLabels:
      app: petitions-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: petitions-exporter
    spec:
      imagePullSecrets:
      - name: pull-docker-images
      containers:
      - name: app
        image: registry.tobys.cloud/petitions-exporter:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
...
