dependencies:
  - name: "concourse"
    version: 6.4.1
    repository: https://kubernetes-charts.storage.googleapis.com/

  - name: "prometheus-operator"
    version: 5.14.1
    repository: https://kubernetes-charts.storage.googleapis.com/
