global:
  cluster:
    name: tobys-cloud

concourse:
  web:
    nameOverride: concourse-web
    additionalVolumes:
      - name: ci-web-configuration
        configMap:
          name: tsp-concourse

    additionalVolumeMounts:
      - name: ci-web-configuration
        mountPath: /web-configuration
  monitor:
    create: true
  worker:
    nameOverride: concourse-worker
    replicas: 2
    hardAntiAffinity: true
    resources: {}
    env:
      - name: CONCOURSE_GARDEN_DNS_PROXY_ENABLE
        value: "false"

      - name: CONCOURSE_WORKER_GARDEN_DNS_PROXY_ENABLE
        value: "false"
  secrets:
    localUsers: admin:password
  concourse:
    worker:
      logLevel: error
      ephemeral: true
      baggageclaim:
        logLevel: error
        driver: overlay
    web:
      logLevel: error
      auth:
        mainTeam:
          localUser: admin
      kubernetes:
        createTeamNamespaces: false
        keepNamespace: false
        namespacePrefix: tsp-system-
      service:
        type: ClusterIP
      prometheus:
        enabled: true
      enablePipelineAuditing: true
      enableTeamAuditing: true
  persistence:
    worker:
      size: 32Gi
  postgresql:
    persistence:
      size: 16Gi

prometheus-operator:
  defaultRules:
    rules:
      general: false
      alertmanager: false

  kubeControllerManager:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeEtcd:
    enabled: false

  prometheus:
    prometheusSpec:
      retention: 120d

      ruleSelectorNilUsesHelmValues: false
      ruleSelector: {}

      secrets: []

      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}

      query:
        timeout: 30s
      additionalScrapeConfigs:

  grafana:
    adminPassword: password

  kubelet:
     serviceMonitor:
       https: true

  alertmanager:
    enabled: false
