commonLabels: {}

additionalPrometheusRules: []

alertmanager:
  enabled: false

grafana:
  enabled: true
  adminPassword: ~

coreDns:
  enabled: true

kubeDns:
  enabled: false

kubeApiServer:
  enabled: false

kubelet:
  enabled: false

nodeExporter:
  enabled: false

prometheusOperator:
  enabled: true

  manageCrds: true

  tlsProxy:
    enabled: true
    image:
      repository: squareup/ghostunnel
      tag: v1.5.2
      sha: ""
      pullPolicy: IfNotPresent
    resources: {}

prometheus:
  enabled: true

  prometheusSpec:
    retention: 365d
    retentionSize: 100GiB
    replicas: 1

    logLevel: info
    logFormat: logfmt

    additionalScrapeConfigs: []

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: do-block-storage
          resources:
            requests:
              storage: 100Gi
