---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bitnami/kubectl
    tag: 1.16

inputs:
  - name: kubeyaml

params:
  NAMESPACE:
  KUBEYAML_PATH:
  SERVER:
  TOKEN:

  CLUSTER_NAME: default

run:
  path: bash
  args:
    - -e
    - -u
    - -o
    - pipefail
    - -c
    - |
      kubectl config \
        set-cluster "$CLUSTER_NAME" \
        --server="$SERVER"

      kubectl apply \
        -n "$NAMESPACE" \
        -f "kubeyaml/$KUBEYAML_PATH"
