---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bitnami/kubectl
    tag: 1.16

inputs:
  - name: kubeyaml

params:
  KUBE_CONFIG:

  RESOURCE:

  NAMESPACE:

run:
  path: bash
  args:
    - -e
    - -u
    - -o
    - pipefail
    - -c
    - |
      mkdir /.kube
      echo "$KUBE_CONFIG" > /.kube/config

      kubectl rollout restart -n "$NAMESPACE" "$RESOURCE"
      kubectl rollout status -n "$NAMESPACE" "$RESOURCE"
