---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bitnami/kubectl
    tag: 1.16

inputs:
  - name: kubeyaml

params:
  KUBEYAML_PATH:

  KUBE_CONFIG:

  NAMESPACE:

run:
  path: bash
  args:
    - -e
    - -u
    - -o
    - pipefail
    - -c
    - |
      mkdir /.kube
      echo "$KUBE_CONFIG" > /.kube/config

      kubectl apply \
        -n "$NAMESPACE" \
        -f "kubeyaml/$KUBEYAML_PATH"
