---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: concourse
  namespace: static-sites
...

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: concourse-static-sites-admin
  namespace: static-sites

subjects:
- kind: ServiceAccount
  name: concourse
  namespace: static-sites

roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
...
