---
apiVersion: v1
kind: Service
metadata:
  name: www-toby-codes
  namespace: static-sites
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: www-toby-codes
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-toby-codes
  namespace: static-sites
spec:
  selector:
    matchLabels:
      app: www-toby-codes
  replicas: 2
  template:
    metadata:
      labels:
        app: www-toby-codes
    spec:
      containers:
      - name: nginx
        image: registry.hub.docker.com/tlwr/www.toby.codes
        ports:
        - containerPort: 80
...

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: www-toby-codes
  namespace: static-sites
spec:
  secretName: www-toby-codes-tls
  dnsNames:
  - toby.codes
  - www.toby.codes
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - toby.codes
      - www.toby.codes
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
...

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: www-toby-codes
  namespace: static-sites
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
    - hosts:
      - toby.codes
      - www.toby.codes
      secretName: www-toby-codes-tls
  rules:
  - host: toby.codes
    http:
      paths:
      - backend:
          serviceName: www-toby-codes
          servicePort: 80
  - host: www.toby.codes
    http:
      paths:
      - backend:
          serviceName: www-toby-codes
          servicePort: 80
...
